// flow-typed signature: 7534228d5cb9b9a867ce37a0654b8ecf
// flow-typed version: <<STUB>>/conventional-commits-parser_v^3.0.8/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conventional-commits-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'conventional-commits-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'conventional-commits-parser/cli' {
  declare module.exports: any;
}

declare module 'conventional-commits-parser/lib/parser' {
  declare module.exports: any;
}

declare module 'conventional-commits-parser/lib/regex' {
  declare module.exports: any;
}

// Filename aliases
declare module 'conventional-commits-parser/cli.js' {
  declare module.exports: $Exports<'conventional-commits-parser/cli'>;
}
declare module 'conventional-commits-parser/index' {
  declare module.exports: $Exports<'conventional-commits-parser'>;
}
declare module 'conventional-commits-parser/index.js' {
  declare module.exports: $Exports<'conventional-commits-parser'>;
}
declare module 'conventional-commits-parser/lib/parser.js' {
  declare module.exports: $Exports<'conventional-commits-parser/lib/parser'>;
}
declare module 'conventional-commits-parser/lib/regex.js' {
  declare module.exports: $Exports<'conventional-commits-parser/lib/regex'>;
}
