// flow-typed signature: 68f2ef48837c06d774af1206be2fced9
// flow-typed version: <<STUB>>/fetch-mock_v^8.3.1/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-mock/cjs/client-legacy' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/client' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/lib/compile-route' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/lib/fetch-handler' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/lib/generate-matcher' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/lib' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/lib/inspecting' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/lib/request-utils' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/lib/response-builder' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/lib/set-up-and-tear-down' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/lib/status-text' {
  declare module.exports: any;
}

declare module 'fetch-mock/cjs/server' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/client-bundle' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/client-legacy-bundle' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/client-legacy' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/client' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/compile-route' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/fetch-handler' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/generate-matcher' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/inspecting' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/request-utils' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/response-builder' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/set-up-and-tear-down' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/lib/status-text' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-mock/cjs/client-legacy.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/client-legacy'>;
}
declare module 'fetch-mock/cjs/client.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/client'>;
}
declare module 'fetch-mock/cjs/lib/compile-route.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib/compile-route'>;
}
declare module 'fetch-mock/cjs/lib/fetch-handler.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib/fetch-handler'>;
}
declare module 'fetch-mock/cjs/lib/generate-matcher.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib/generate-matcher'>;
}
declare module 'fetch-mock/cjs/lib/index' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib'>;
}
declare module 'fetch-mock/cjs/lib/index.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib'>;
}
declare module 'fetch-mock/cjs/lib/inspecting.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib/inspecting'>;
}
declare module 'fetch-mock/cjs/lib/request-utils.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib/request-utils'>;
}
declare module 'fetch-mock/cjs/lib/response-builder.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib/response-builder'>;
}
declare module 'fetch-mock/cjs/lib/set-up-and-tear-down.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib/set-up-and-tear-down'>;
}
declare module 'fetch-mock/cjs/lib/status-text.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/lib/status-text'>;
}
declare module 'fetch-mock/cjs/server.js' {
  declare module.exports: $Exports<'fetch-mock/cjs/server'>;
}
declare module 'fetch-mock/es5/client-bundle.js' {
  declare module.exports: $Exports<'fetch-mock/es5/client-bundle'>;
}
declare module 'fetch-mock/es5/client-legacy-bundle.js' {
  declare module.exports: $Exports<'fetch-mock/es5/client-legacy-bundle'>;
}
declare module 'fetch-mock/es5/client-legacy.js' {
  declare module.exports: $Exports<'fetch-mock/es5/client-legacy'>;
}
declare module 'fetch-mock/es5/client.js' {
  declare module.exports: $Exports<'fetch-mock/es5/client'>;
}
declare module 'fetch-mock/es5/lib/compile-route.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/compile-route'>;
}
declare module 'fetch-mock/es5/lib/fetch-handler.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/fetch-handler'>;
}
declare module 'fetch-mock/es5/lib/generate-matcher.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/generate-matcher'>;
}
declare module 'fetch-mock/es5/lib/index' {
  declare module.exports: $Exports<'fetch-mock/es5/lib'>;
}
declare module 'fetch-mock/es5/lib/index.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib'>;
}
declare module 'fetch-mock/es5/lib/inspecting.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/inspecting'>;
}
declare module 'fetch-mock/es5/lib/request-utils.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/request-utils'>;
}
declare module 'fetch-mock/es5/lib/response-builder.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/response-builder'>;
}
declare module 'fetch-mock/es5/lib/set-up-and-tear-down.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/set-up-and-tear-down'>;
}
declare module 'fetch-mock/es5/lib/status-text.js' {
  declare module.exports: $Exports<'fetch-mock/es5/lib/status-text'>;
}
declare module 'fetch-mock/es5/server.js' {
  declare module.exports: $Exports<'fetch-mock/es5/server'>;
}
