// flow-typed signature: 68eb702881af4c10f4e11f233f5afe66
// flow-typed version: <<STUB>>/git-cz_v^3.3.0/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-cz'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-cz' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-cz/bin/git-cz' {
  declare module.exports: any;
}

declare module 'git-cz/dist/cli' {
  declare module.exports: any;
}

declare module 'git-cz/dist/cz' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-cz/bin/git-cz.js' {
  declare module.exports: $Exports<'git-cz/bin/git-cz'>;
}
declare module 'git-cz/dist/cli.js' {
  declare module.exports: $Exports<'git-cz/dist/cli'>;
}
declare module 'git-cz/dist/cz.js' {
  declare module.exports: $Exports<'git-cz/dist/cz'>;
}
