// flow-typed signature: 6265220d7cb9e6f1892e571abe7abc0e
// flow-typed version: <<STUB>>/react-use-dimensions_v^1.2.1/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-use-dimensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-use-dimensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-use-dimensions/es' {
  declare module.exports: any;
}

declare module 'react-use-dimensions/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-use-dimensions/es/index' {
  declare module.exports: $Exports<'react-use-dimensions/es'>;
}
declare module 'react-use-dimensions/es/index.js' {
  declare module.exports: $Exports<'react-use-dimensions/es'>;
}
declare module 'react-use-dimensions/lib/index' {
  declare module.exports: $Exports<'react-use-dimensions/lib'>;
}
declare module 'react-use-dimensions/lib/index.js' {
  declare module.exports: $Exports<'react-use-dimensions/lib'>;
}
